language: go
sudo: required

services:
  - docker
go:
  - 1.8
  - 1.9
  - "1.10"

script:
  - make test

deploy:
  provider: releases
  skip_cleanup: true
  #api_key: $GH_TOKEN
  file_glob: true
  #file:
  on:
    tags: true

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
